### ISSUE TITLE
Theming support

### ISSUE THREAD

**Issue by Eisenwave** [Eisenwave/ulight#40]
µlight should be bundled with a few themes that work with the token types it generates.

Note that the textual IDs can be found here
https://github.com/Eisenwave/ulight/blob/fec5da46ac01f3e07110b9871189277a5550bca5/include/ulight/ulight.hpp#L108-L159

https://github.com/Eisenwave/ulight/blob/main/www/css/code.css contains an example of CSS which works with that.

## Why not just use CSS themes?

However, it isn't a good idea to use CSS as the "source of truth" for themes for a few reasons:

- This innately ties µlight themes to HTML output, but µlight gives you access to the underlying highlighting tokens, and you can choose to do whatever you want with them. You should also be able to dump those tokens into a console with RGB color support for example, or into a text editor, so you don't always use CSS.
- CSS is very powerful, an extracting information out of it is difficult.
- On the modern web, you often want to respond to dark/light/print mode with different theme variants. The details of how a page does that can vary quite a bit. For example, you can just accept to `prefers-dark-theme` media queries, but you can also offer manual override by adding a class to a code block, to `<main>`, `<html>`, or whatver. The theme should offer you the ability to generate the necessary CSS files to set it up however you want.

## Vision for themes

My idea is as to define themes in JSON files, containing a family of themes, as follows:
```json
{
    "light": {
        "background": "white",
        "foreground": "black",
        "kw": "red"
    },
    "dark": {
        "background": "#202020",
        "foreground": "#f0f0f0",
        "kw": "pink"
    }
}
```
Basically, the top-level object contains a map of theme variants onto a map of rules. The following variants may be useful:
<dl>
<dt>light</dt>
<dd>Colorful light theme</dd>
<dt>dark</dt>
<dd>Colorful dark theme.</dd>
<dt>grayscale</dt>
<dd>Grayscale theme. Useful for print media with no color support.</dd>
<dt>dark_high_contrast</dt>
<dd>High-contrast dark theme.</dd>
</dl>

From this, you could generate CSS like:
```css
@media (prefers-color-scheme: light) {
    pre {
        background-color: white;
        color: black;
    }
    h-[data-h^=kw] { color: red; }
}
@media (prefers-color-scheme: dark) {
    pre {
        "background": "#202020",
        "color": "f0f0f0"
    }
    h-[data-h^=kw] { color: pink; }
}
```
Note that `h-[data-h^=kw]` selects any `<h->` element with a `data-h` attribute whose values starts with `kw`. In other words, that selector applies to any kind of keyword.
